version: '3'

services:

  flexget:
    image: activ/arch-flexget
    container_name: flexget
    hostname: flexget
    ports:
      - "3539:3539"
    volumes:
      - ${CONFIG}/flexget:/config
      - ${DOWNLOAD}/watch:/watch
    environment:
      WEB_PASSWD: "pNTgQj4hfJPPiGVFt9re"
    labels:
      traefik.enable: "true"
      traefik.port: "3539"
      traefik.frontend.rule: "Host:flexget.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
